### PR TITLE
internationalization

### PR DESCRIPTION
**Pull request by SomtochiUmeh**
- [x] Multilanguage support - currently testing with english and spanish
- [x] All user-facing text fields are converted to their choice language (set in system settings)
- [x] I used [Flutter Intl](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) extension on VSCode to help with the process. They have [a quick way](https://x.com/localizely/status/1255175275454881793) of extracting strings to .arb files.
- [x] I had to move around a couple of things since I need to pass context to be able to use localization. For example, I removed all the consts from Text widgets, and for all the constant classes, I had to pass context and change all the static methods to gets.

https://github.com/user-attachments/assets/30469bbc-4043-4b1b-8091-648005470019

Next steps for this:
- Check with Nikki and Rosanne on what Eritrean language we want to support.
- I saw Arabic and Tigrinya were the main languages, so I'll have to ensure the texts are right to left.

### CODE REVIEW

**Comment by SomtochiUmeh** [comment]
I included some Arabic translations (not everything yet). From the deployment preview, it seems RTL already happens, so maybe this is something I wouldn't have to do manually?
image

**Review by philip-sterne — APPROVED** [review]

**Comment by philip-sterne** [comment]
> I included some Arabic translations (not everything yet). From the deployment preview, it seems RTL already happens, so maybe this is something I wouldn't have to do manually?
> image

Hopefully not. That certainly makes things easier!

Please also add Tigrinya, I believe that is the main language they want to target.

**Comment by SomtochiUmeh** [comment]
Updated this branch with the main branch and persistence changes so far. I still need to work on the dropdowns, so when a user switches languages, it can easily switch persisted feed between the languages. The main issue is that the dropdown values are being stored as translated strings. I'll modify each feed to have an id for the identifier instead of its name in a follow-up commit.

**Comment by SomtochiUmeh** [comment]
Demo showing seamless switching between languages for the dropdowns

https://github.com/user-attachments/assets/3fe87afc-28e4-4117-b130-d96c786c07bb

**Pull request merged**
