### PR TITLE
Resolves #18

### LINKED ISSUE #18: Nikki
Hi my apologies i just looked at the concentrate list and seen that it is incomplete, I have uploaded here the excel doc , could you please just use the fodder and concentrate list from this excel file to update the app.

- on the feed formulation page could you please make the formulation diet table headings in line with the cow requirements meaning the DM, CP etc lines up for easy reading.
- in the feeding guidelines there is an error 
[240827 ration calculator latest ver 01.xlsx](https://github.com/user-attachments/files/16758865/240827.ration.calculator.latest.ver.01.xlsx)
with the dry cow requirements , the CP should be 12% please correct this .
- the paw prints can you change the icon into a cow instead .
if you need more clarification don't hesitate to drop me an email.

Kind regards 
Nikki

### PR DESCRIPTION
**Pull request by SomtochiUmeh**
- [x] Updated fodder and concentrate items
- [x] Changed from the paw icon to a cow svg icon

<table>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by SomtochiUmeh** [comment]
- [x] CP for Dry cow feeding guidelines now 12%

image

**Comment by SomtochiUmeh** [comment]
- [x] Changed app icon / launcher to the cow image and app name to RationApp

image

**Comment by SomtochiUmeh** [comment]
Adjusted the app to scroll in landscape mode. The issue of `feed_formula_page.dart` not being scrollable in landscape came from the CowRequirements and Totals sections being being fixed on the screen, so they took up all the space such that we couldn't see the scrollable Fodder and Concentrate sections.
To handle this, I made the CowRequirements and Totals sections not fixed in landscape mode, but still fixed in portrait mode.
I also adjusted the CowRequirements popup AlertDialog to be scrollable.

**Comment by SomtochiUmeh** [comment]
Adjusted the AddIngredientDialog to be scrollable in landscape mode


https://github.com/user-attachments/assets/0eaf016b-d699-46b5-8f11-a4ff2b7cefae

**Review by philip-sterne — APPROVED** [review]
This looks fine, but I would suggest reworking the icons. The cow looks a bit squished. Maybe zoom in on the cow's head, so that the aspect ratio is unchanged, and the icon is square.

Feel free to merge.

**Pull request merged**
